# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6ca9388d5b2893d094cd176b1dcdc9c8d744401766b5a4e13f402d0d2817f013d8861ff9bd4c0dc2e773422b4890cf640caac402c707df24ad038900abad42d

test:
  secret_key_base: df2a159e8ef8998b32c16be87a94621f78eec101cc9b71c47b07871ff86d4f0a90dc647bae49f92219e021259264d5cdb9d8f62801a8a4d1638fa741dd160e28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
